# SITE CONFIGURATION
title: Lengary's site # your site title
author: Lengary # You :P
description: > # Meta description of Homepage
  Follow the notes upon the journey
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coderlengary.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Categories', link: '/categories'}
  - {name: 'Links', link: '/links'}
  - {name: 'About', link: '/about'}

tagline: >
  Follow the notes upon the journey. At first sight marks one's destiny.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

# email: your-email@domain.com # email for form submission

github_username:  CoderLengary # replace with your_github_username or comment to remove link from footer

# disqus:
  # shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
